export const GameSixApi=[
  {
    id:1,
    img:"/gl1.png",
    title:"Sniper Fury - Elite",
    mark:"Shooter",
    ratingNo:"380",
    popular:"trending",
    category:"shooter",
    free:"Included",  
  },
  {
  id:2,
  img:"/gl2.png",
  title:"Angry Birds 2",
  mark:"Action & adventure",
  popular:"trending",
  category:"action",
  ratingNo:"5k",
  free:"Included",  
  },
  {
    id:3,
    img:"/gl3.png",
    title:"Modern Combat 5:Blackout",
    mark:"Fighting",
    ratingNo:"4",
    popular:"trending",
    category:"fighting",
    free:"Included",  
  },
  {
    id:4,
    img:"/gl4.png",
    title:"Gangster New Orleans",
    mark:"Fighting",
    popular:"trending",
    category:"fighting",
    ratingNo:"5k",
    free:"Free",  
  },
  {
    id:5,
    img:"/gl5.png",
    title:"Township",
    mark:"Classics",
    popular:"trending",
    category:"classic",
    ratingNo:"1k",
    free:"Owned",  
  },
 
]
export const GameSevenApi=[
  {
    id:6,
    img:"/gl6.png",
    title:"Beach buggy racing",
    mark:"Racing & flying",
    ratingNo:"673",
    popular:"trending",
    category:"racing",
    free:"Included",  
  },
  {
    id:7,
    img:"/gl7.png",
    title:"Mystery Manor:Hidden",
    mark:"Action & adventure",
    popular:"trending",
    category:"action",
    ratingNo:"1k",
    free:"Free",  
  },
  {
    id:8,
    img:"/gl8.png",
    title:"Sacred Legend",
    mark:"Fighting",
    ratingNo:"899",
    popular:"trending",
    category:"fighting",
    free:"Free",  
  },
  {
    id:9,
    img:"/gl9.png",
    title:"Hitman 3",
    mark:"Action & adventure",
    popular:"trending",
    category:"action",
    ratingNo:"455",
    free:"$110",  
  },
  {
    id:10,
    img:"/gl10.png",
    title:"Free fire booyah day",
    mark:"Action & adventure",
    popular:"trending",
    category:"action",
    ratingNo:"1k",
    free:"Free",  
  },
  
]


const AllGamesApi=[
    {
    id:1,
    img:"/gl1.png",
    title:"Sniper Fury - Elite",
    mark:"Shooter",
    ratingNo:"380",
    popular:"trending",
    category:"shooter",
    free:"Included",  
  },
  {
  id:2,
  img:"/gl2.png",
  title:"Angry Birds 2",
  mark:"Action & adventure",
  popular:"trending",
  category:"action",
  ratingNo:"5k",
  free:"Included",  
  },
  {
    id:3,
    img:"/gl3.png",
    title:"Modern Combat 5:Blackout",
    mark:"Fighting",
    ratingNo:"4",
    popular:"trending",
    category:"fighting",
    free:"Included",  
  },
  {
    id:4,
    img:"/gl4.png",
    title:"Gangster New Orleans",
    mark:"Fighting",
    popular:"trending",
    category:"fighting",
    ratingNo:"5k",
    free:"Free",  
  },
  {
    id:5,
    img:"/gl5.png",
    title:"Township",
    mark:"Classics",
    popular:"trending",
    category:"classic",
    ratingNo:"1k",
    free:"Owned",  
  },
  {
    id:6,
    img:"/gl6.png",
    title:"Beach buggy racing",
    mark:"Racing & flying",
    ratingNo:"673",
    popular:"trending",
    category:"racing",
    free:"Included",  
  },
  {
    id:7,
    img:"/gl7.png",
    title:"Mystery Manor:Hidden",
    mark:"Action & adventure",
    popular:"trending",
    category:"action",
    ratingNo:"1k",
    free:"Free",  
  },
  {
    id:8,
    img:"/gl8.png",
    title:"Sacred Legend",
    mark:"Fighting",
    ratingNo:"899",
    popular:"trending",
    category:"fighting",
    free:"Free",  
  },
  {
    id:9,
    img:"/gl9.png",
    title:"Hitman 3",
    mark:"Action & adventure",
    popular:"trending",
    category:"action",
    ratingNo:"455",
    free:"$110",  
  },
  {
    id:10,
    img:"/gl10.png",
    title:"Free fire booyah day",
    mark:"Action & adventure",
    popular:"trending",
    category:"action",
    ratingNo:"1k",
    free:"Free",  
  },
  
    {
    id:11,
    img:"/gl11.png",
    title:"Worlds of tank Blitz",
    mark:"Shooter",
    ratingNo:"380",
    popular:"trending",
    category:"shooter",
    free:"Included",  
  },
  {
  id:12,
  img:"/gl12.png",
  title:"Monster legend",
  mark:"Classics",
  popular:"special",
  category:"classic",
  ratingNo:"5k",
  free:"Included",  
  },
  {
    id:13,
    img:"/gl13.png",
    title:"Overkill 3",
    mark:"Fighting",
    ratingNo:"4",
    popular:"special",
    category:"fighting",
    free:"Included",  
  },
  {
    id:14,
    img:"/gl14.png",
    title:"PSYCHOPOMP",
    mark:"Classics",
    popular:"special",
    category:"classic",
    ratingNo:"5k",
    free:"Free",  
  },
  {
    id:15,
    img:"/gl15.png",
    title:"Destiny 2",
    mark:"Action & adventure",
    popular:"special",
    category:"action",
    ratingNo:"1k",
    free:"Owned",  
  },
  {
    id:16,
    img:"/gl16.png",
    title:"Hello neighbour 2",
    mark:"Action & adventure",
    ratingNo:"673",
    popular:"special",
    category:"action",
    free:"Included",  
  },
  {
    id:17,
    img:"/gl17.png",
    title:"Raid : Shadow legend",
    mark:"Classics",
    popular:"special",
    category:"classic",
    ratingNo:"1k",
    free:"Free",  
  },
  {
    id:18,
    img:"/gl18.png",
    title:"Spongebob",
    mark:"Classics",
    ratingNo:"899",
    popular:"special",
    category:"classic",
    free:"Free",  
  },
  {
    id:19,
    img:"/gl19.png",
    title:"Desease Infected",
    mark:"Shooter",
    popular:"special",
    category:"shooter",
    ratingNo:"455",
    free:"$110",  
  },
  {
    id:20,
    img:"/gl20.png",
    title:"Tank force 3D",
    mark:"Action & adventure",
    popular:"special",
    category:"action",
    ratingNo:"1k",
    free:"Free",  
  },
  
    {
    id:90,
    img:"/x1.png",
    title:"Grounded - Game Preview",
    mark:"Action & adventure",
    ratingNo:"380",
    popular:"best-rated",
    category:"action",
    free:"Included",  
  },
  {
  id:91,
  img:"/x2.png",
  title:"Microsoft Flight Simulator",
  mark:"Racing & flying",
  popular:"best-rated",
  category:"racing",
  ratingNo:"5k",
  free:"Included",  
  },
  {
    id:92,
    img:"/x3.png",
    title:"Halo infinite(campaign)",
    mark:"Shooter",
    ratingNo:"4",
    popular:"best-rated",
    category:"shooter",
    free:"Included",  
  },
  {
    id:93,
    img:"/x4.png",
    title:"Wasteland 3",
    mark:"Role playing",
    popular:"best-rated",
    category:"classic",
    ratingNo:"5k",
    free:"Free",  
  },
  {
    id:94,
    img:"/x5.png",
    title:"Halo infinite",
    mark:"Shooter",
    popular:"best-rated",
    category:"shooter",
    ratingNo:"1k",
    free:"Owned",  
  },
  {
    id:95,
    img:"/x6.png",
    title:"Psychonauts 2",
    mark:"Action & adventure",
    ratingNo:"673",
    popular:"best-rated",
    category:"action",
    free:"Included",  
  },
  {
    id:96,
    img:"/x7.png",
    title:"Gear of war",
    mark:"Shooter",
    popular:"best-rated",
    category:"shooter",
    ratingNo:"1k",
    free:"Free",  
  },
  {
    id:97,
    img:"/x8.png",
    title:"ORI - the collection",
    mark:"Action & adventure",
    ratingNo:"899",
    popular:"best-rated",
    category:"action",
    free:"Free",  
  },
  {
    id:98,
    img:"/x9.png",
    title:"Day of the tantacle",
    mark:"Action",
    popular:"best-rated",
    category:"action",
    ratingNo:"455",
    free:"$110",  
  },
  {
    id:99,
    img:"/x10.png",
    title:"Call of duty",
    mark:"Grim fandango Remasterd",
    popular:"best-rated",
    category:"action",
    ratingNo:"1k",
    free:"Free",  
  },
  {
    id:28,
    img:"/gg1.png",
    title:"Resident evil",
    popular:"popular",
    category:"shooting",
    mark:"Shooting",
    ratingNo:"380",
    free:"Free",  
  },
  {
  id:29,
  img:"/gg2.png",
  title:"Minecraft for windows 10 starter Collection",
  mark:"Action & adventure",
  popular:"popular",
  category:"action",
  ratingNo:"5k",
  free:"$97",  
  },
  {
    id:30,
    img:"/gg3.png",
    title:"Clash of Empire: Epic strategy War game",
    mark:"Action & adventure +2",
    popular:"popular",
    category:"action",
    ratingNo:"4",
    free:"Free",  
  },
  {
    id:31,
    img:"/gg4.png",
    title:"Aspahlt-9 Legends",
    mark:"Racing & Flying +2",
    popular:"popular",
    category:"racing",
    ratingNo:"5k",
    free:"Owned",  
  },
  {
    id:32,
    img:"/gg5.png",
    title:"Candy crush Saga ",
    mark:"Puzzle & Trivia",
    popular:"popular",
    category:"classic",
    ratingNo:"1k",
    free:"Owned",  
  },
  {
    id:33,
    img:"/gg6.png",
    title:"Roblox",
    mark:"Action & adventure",
    popular:"best-rated",
    category:"action",
    ratingNo:"673",
    free:"Free",  
  },
  {
    id:34,
    img:"/gg7.png",
    title:"Kiss of war ",
    mark:"Action & adventure",
    popular:"popular",
    category:"action",
    ratingNo:"1k",
    free:"Free",  
  },
  {
    id:35,
    img:"/gg8.png",
    title:"Just Cause 2",
    mark:"Action & Shooting",
    popular:"best-rated",
    category:"shooting",
    ratingNo:"899",
    free:"Free",  
  },
  {
    id:36,
    img:"/gg9.png",
    title:"Lord of the rings",
    mark:"Shooting",
    popular:"popular",
    category:"shooting",
    ratingNo:"455",
    free:"$110",  
  },
  {
    id:37,
    img:"/gg10.png",
    title:"Call of duty",
    mark:"Mission & Rescue",
    popular:"popular",
    category:"classic",
    ratingNo:"1k",
    free:"Free",  
  },
  
  ]
  export default AllGamesApi;