const gameApi=[{
    id:1,
    img:"/cc1.png",
    title:"Whatsapp Desktop",
    mark:"social",
    ratingNo:"199",
    free:"Free",
},
{
    id:2,
    img:"/cc2.png",
    title:"Telegram Desktop",
    mark:"social",
    ratingNo:"215",
    free:"Free",  
},
{
    id:3,
    img:"/cc3.png",
    title:"Amazon Prime Video",
    mark:"Entertainment",
    ratingNo:"433",
    free:"Free",  
},
{
    id:4,
    img:"/cc4.png",
    title:"Netflix",
    mark:"Entertainment",
    ratingNo:"673",
    free:"Free",  
},
{
    id:5,
    img:"/cc5.png",
    title:"Instagram",
    mark:"social",
    ratingNo:"235",
    free:"Free",  
},
{
    id:6,
    img:"/cc7.png",
    title:"Crunchyroll",
    mark:"Entertainment",
    ratingNo:"735",
    free:"Free",  
}
]
// ...2---


const gameApi3=[{
    id:7,
    img:"/cc3.png",
    title:"Amazon Prime Video",
    mark:"Entertainment",
    ratingNo:"433",
    free:"Free",  
},
{
  id:8,
  img:"/cc4.png",
  title:"Netflix",
  mark:"Entertainment",
  ratingNo:"673",
  free:"Free",  
},
{
    id:9,
    img:"/cc7.png",
    title:"Crunchyroll",
    mark:"Entertainment",
    ratingNo:"735",
    free:"Free",  
},
{
    id:10,
    img:"/ce5.png",
    title:"Movies & Tv",
    mark:"Photo & vedio",
    ratingNo:"673",
    free:"Free",  
},
{
    id:11,
    img:"/ce6.png",
    title:"zTwicth - Twicth app",
    mark:"Entertainment",
    ratingNo:"235",
    free:"Free",  
},
{
    id:12,
    img:"/ce7.png",
    title:"NetTv Plus",
    mark:"Entertainment",
    ratingNo:"754",
    free:"Free",  
}
]
export const gameApiEx2=[{
  id:7,
  img:"/al7.png",
  title:"Picsart Photo editor",
  mark:"photo & video",
  ratingNo:"673",
  category:"tools",
  popular:"free",
  free:"Free",   
},
{
id:8,
img:"/al8.png",
title:"Group me ",
mark:"Personalization",
category:"Personalization",
popular:"trending",
ratingNo:"215",
free:"Free",  
},
{
  id:9,
  img:"/al9.png",
  title:"Night skies PREMIUM",
  mark:"Personalization",
  ratingNo:"735",
  category:"Personalization",
  popular:"popular",
  free:"Free",  
},
{
  id:10,
  img:"/al10.png",
  title:"PowerBt desktop",
  mark:"Productivity",
  ratingNo:"673",
  category:"productivity",
  popular:"selling",
  free:"Included",  
},
{
  id:11,
  img:"/al11.png",
  title:"Office",
  mark:"Productivity",
  category:"Productivity",
  popular:"popular",
  ratingNo:"423",
  free:"Free",   
},
{
  id:12,
  img:"/al12.png",
  title:"To do Micosoft",
  mark:"Productivity",
  ratingNo:"199",
  category:"Productivity",
  popular:"trending",
  free:"Free",
},
]
export const gameApiEx1=[{
  id:15,
  img:"/al15.png",
  title:"Files app",
  mark:"Productivity",
  category:"Productivity",
  popular:"trending",
  ratingNo:"673",
  free:"Free",  
},
{
  id:16,
  img:"/al16.png",
  title:"Unigram windows",
  mark:"Social",
  ratingNo:"235",
  category:"entertainment",
  popular:"popular",
  free:"Installed",  
},
{
  id:17,
  img:"/al17.png",
  title:"Blender",
  mark:"Multimedia",
  ratingNo:"735",
  category:"tools",
  popular:"free",
  free:"Free",  
},
{
  id:18,
  img:"/al18.png",
  title:"Xbox - handler",
  mark:"Entertainment",
  ratingNo:"673",
  category:"entertainment",
  popular:"selling",
  free:"Free",   
},
{
id:19,
img:"/al19.png",
title:"Avast antivirus",
mark:"Productivity",
category:"productivity",
popular:"popular",
ratingNo:"215",
free:"Free",  
},
{
  id:20,
  img:"/al20.png",
  title:"*Zip best - achiever",
  mark:"Tools",
  ratingNo:"735",
  category:"tools",
  popular:"trending",
  free:"Free",  
},
]
// 222
const gameApi4=[{
    id:13,
    img:"/cc3.png",
    title:"Amazon Prime Video",
    mark:"Entertainment",
    ratingNo:"433",
    free:"Free",  
},
{
  id:14,
  img:"/ce2.png",
  title:"Dolby Access best Decorator",
  mark:"Apps and Entertainment",
  ratingNo:"215",
  free:"Free",  
},
{
    id:15,
    img:"/ce8.png",
    title:"Discord",
    mark:"Social",
    ratingNo:"735",
    free:"Free",  
},
{
    id:16,
    img:"/ce9.png",
    title:"Spotify - Music and Podcast ",
    mark:"Music",
    ratingNo:"673",
    free:"Free",  
}
]

// 5../
const gameApi5=[{
  id:17,
  img:"/gg1.png",
  title:"Resident evil",
  mark:"Action",
  ratingNo:"380",
  free:"Free",  
},
{
id:19,
img:"/gg2.png",
title:"Minecraft for windows 10 starter Collection",
mark:"Action & adventure",
ratingNo:"5k",
free:"$97",  
},
{
  id:20,
  img:"/gg3.png",
  title:"Clash of Empire: Epic strategy War game",
  mark:"Action & adventure +2",
  ratingNo:"4",
  free:"Free",  
},
{
  id:21,
  img:"/gg5.png",
  title:"Aspahlt-9 Legends",
  mark:"Racing & Flying +2",
  ratingNo:"5k",
  free:"Owned",  
},
{
  id:22,
  img:"/gg4.png",
  title:"Candy crush Saga ",
  mark:"Puzzle & Trivia",
  ratingNo:"1k",
  free:"Owned",  
},
{
  id:23,
  img:"/gg6.png",
  title:"Roblox",
  mark:"Action & adventure",
  ratingNo:"673",
  free:"Free",  
}
]

// 6;;
const gameApi6=[{
  id:24,
  img:"/gs1.png",
  title:"Super mario",
  mark:"adventure",
  ratingNo:"433",
  free:"Free",  
},
{
id:25,
img:"/gs2.png",
title:"Stomania - free casino Slots",
mark:"Casino",
ratingNo:"288",
free:"Free",  
},

{
  id:26,
  img:"/gs3.png",
  title:"Solitaire cruise Card game ",
  mark:"Card & board",
  ratingNo:"673",
  free:"Free",  
},
{
  id:27,
  img:"/gs4.png",
  title:"Big far - Mobile harvest",
  mark:"Simulation",
  ratingNo:"735",
  free:"Free",  
}
]
// 7...
const gameApi7=[{
  id:28,
  img:"/gg1.png",
  title:"Resident evil",
  mark:"Action",
  ratingNo:"380",
  free:"Free",  
},
{
id:29,
img:"/gg2.png",
title:"Minecraft for windows 10 starter Collection",
mark:"Action & adventure",
ratingNo:"5k",
free:"$97",  
},
{
  id:30,
  img:"/gg3.png",
  title:"Clash of Empire: Epic strategy War game",
  mark:"Action & adventure +2",
  ratingNo:"4",
  free:"Free",  
},
{
  id:31,
  img:"/gg4.png",
  title:"Aspahlt-9 Legends",
  mark:"Racing & Flying +2",
  ratingNo:"5k",
  free:"Owned",  
},
{
  id:32,
  img:"/gg5.png",
  title:"Candy crush Saga ",
  mark:"Puzzle & Trivia",
  ratingNo:"1k",
  free:"Owned",  
},
{
  id:33,
  img:"/gg6.png",
  title:"Roblox",
  mark:"Action & adventure",
  ratingNo:"673",
  free:"Free",  
},
{
  id:34,
  img:"/gg7.png",
  title:"Kiss of war ",
  mark:"Action & adventure",
  ratingNo:"1k",
  free:"Free",  
},
{
  id:35,
  img:"/gg8.png",
  title:"Just Cause 2",
  mark:"Action & Mission",
  ratingNo:"899",
  free:"Free",  
},
{
  id:36,
  img:"/gg9.png",
  title:"Lord of the rings",
  mark:"Action",
  ratingNo:"455",
  free:"$110",  
},
{
  id:37,
  img:"/gg10.png",
  title:"Call of duty",
  mark:"Mission & Rescue",
  ratingNo:"1k",
  free:"Free",  
},
{
  id:38,
  img:"/gg1.png",
  title:"Resident evil",
  mark:"Action",
  ratingNo:"380",
  free:"Free",  
},
{
id:39,
img:"/gg2.png",
title:"Minecraft for windows 10 starter Collection",
mark:"Action & adventure",
ratingNo:"5k",
free:"$97",  
},
{
  id:40,
  img:"/gg3.png",
  title:"Clash of Empire: Epic strategy War game",
  mark:"Action & adventure +2",
  ratingNo:"4",
  free:"Free",  
},
{
  id:41,
  img:"/gg4.png",
  title:"Aspahlt-9 Legends",
  mark:"Racing & Flying +2",
  ratingNo:"5k",
  free:"Owned",  
},
{
  id:42,
  img:"/gg5.png",
  title:"Candy crush Saga ",
  mark:"Puzzle & Trivia",
  ratingNo:"1k",
  free:"Owned",  
},
{
  id:43,
  img:"/gg6.png",
  title:"Roblox",
  mark:"Action & adventure",
  ratingNo:"673",
  free:"Free",  
},
{
  id:44,
  img:"/gg7.png",
  title:"Kiss of war ",
  mark:"Action & adventure",
  ratingNo:"1k",
  free:"Free",  
},
{
  id:45,
  img:"/gg8.png",
  title:"Just Cause 2",
  mark:"Action & Mission",
  ratingNo:"899",
  free:"Free",  
},
{
  id:46,
  img:"/gg9.png",
  title:"Lord of the rings",
  mark:"Action",
  ratingNo:"455",
  free:"$110",  
},
{
  id:47,
  img:"/gg10.png",
  title:"Call of duty",
  mark:"Mission & Rescue",
  ratingNo:"1k",
  free:"Free",  
},
]

// 888
const gameApi8=[{
  id:49,
  img:"/cc1.png",
  title:"Whatsapp Desktop",
  mark:"social",
  ratingNo:"199",
  free:"Free",
},
{
  id:50,
  img:"/cc2.png",
  title:"Telegram Desktop",
  mark:"social",
  ratingNo:"215",
  free:"Free",  
},
{
  id:51,
  img:"/cc3.png",
  title:"Amazon Prime Video",
  mark:"Entertainment",
  ratingNo:"433",
  free:"Free",  
},
{
  id:52,
  img:"/cc4.png",
  title:"Netflix",
  mark:"Entertainment",
  ratingNo:"673",
  free:"Free",  
},
{
  id:53,
  img:"/cc5.png",
  title:"Instagram",
  mark:"social",
  ratingNo:"235",
  free:"Free",  
},
{
  id:54,
  img:"/cc7.png",
  title:"Crunchyroll",
  mark:"Entertainment",
  ratingNo:"735",
  free:"Free",  
},
{
  id:55,
  img:"/ce5.png",
  title:"Movies & Tv",
  mark:"Photo & vedio",
  ratingNo:"673",
  free:"Free",   
},
{
id:56,
img:"/ce2.png",
title:"Dolby Access best Decorator",
mark:"Apps and Entertainment",
ratingNo:"215",
free:"Free",  
},
{
  id:57,
  img:"/ce8.png",
  title:"Discord",
  mark:"Social",
  ratingNo:"735",
  free:"Free",  
},
{
  id:58,
  img:"/ce9.png",
  title:"Spotify - Music and Podcast ",
  mark:"Music",
  ratingNo:"673",
  free:"Free",  
},
{
  id:59,
  img:"/ce3.png",
  title:"Adobe creative Cloud express",
  mark:"Apps . Multimedia design",
  ratingNo:"423",
  free:"Free",   
}
]
// 9999
const gameApi9=[{
  id:59,
  img:"/con1.png",
  title:"Tumbler",
  mark:"social",
  ratingNo:"199",
  free:"Free",
},
{
  id:60,
  img:"/con2.png",
  title:"Twitter",
  mark:"social",
  ratingNo:"215",
  free:"Free",  
},
{
  id:61,
  img:"/con3.png",
  title:"Reddit",
  mark:"Entertainment",
  ratingNo:"433",
  free:"Free",  
},
{
  id:62,
  img:"/con4.png",
  title:"Tuneln",
  mark:"Radio",
  ratingNo:"673",
  free:"Free",  
},
{
  id:63,
  img:"/con5.png",
  title:"Micosoft news",
  mark:"News & weather",
  ratingNo:"235",
  free:"Free",  
},
{
  id:64,
  img:"/con6.png",
  title:"Zoom cloud meeting",
  mark:"Productivity",
  ratingNo:"735",
  free:"Free",  
},
{
  id:65,
  img:"/con7.png",
  title:"Hotspot shield vpn",
  mark:"Productivity",
  ratingNo:"673",
  free:"Free",   
},
{
id:66,
img:"/con8.png",
title:"Group me ",
mark:"Social",
ratingNo:"215",
free:"Free",  
},
{
  id:67,
  img:"/con9.png",
  title:"Messenger",
  mark:"Social",
  ratingNo:"735",
  free:"Free",  
},
{
  id:68,
  img:"/con10.png",
  title:"Pintrest",
  mark:"Music",
  ratingNo:"673",
  free:"Free",  
},
{
  id:69,
  img:"/con11.png",
  title:"Flipboard",
  mark:"Social",
  ratingNo:"423",
  free:"Free",   
},
{
  id:70,
  img:"/cc1.png",
  title:"Whatsapp Desktop",
  mark:"social",
  ratingNo:"199",
  free:"Free",
},
{
  id:71,
  img:"/cc2.png",
  title:"Telegram Desktop",
  mark:"social",
  ratingNo:"215",
  free:"Free",  
},
{
  id:72,
  img:"/cc3.png",
  title:"Amazon Prime Video",
  mark:"Entertainment",
  ratingNo:"433",
  free:"Free",  
},
{
  id:73,
  img:"/cc4.png",
  title:"Netflix",
  mark:"Entertainment",
  ratingNo:"673",
  free:"Free",  
},
{
  id:74,
  img:"/cc5.png",
  title:"Instagram",
  mark:"social",
  ratingNo:"235",
  free:"Free",  
},
{
  id:75,
  img:"/cc7.png",
  title:"Crunchyroll",
  mark:"Entertainment",
  ratingNo:"735",
  free:"Free",  
},
{
  id:76,
  img:"/ce5.png",
  title:"Movies & Tv",
  mark:"Photo & vedio",
  ratingNo:"673",
  free:"Free",   
},
{
id:77,
img:"/ce2.png",
title:"Dolby Access best Decorator",
mark:"Apps and Entertainment",
ratingNo:"215",
free:"Free",  
},
{
  id:78,
  img:"/ce8.png",
  title:"Discord",
  mark:"Social",
  ratingNo:"735",
  free:"Free",  
},
{
  id:79,
  img:"/ce9.png",
  title:"Spotify - Music and Podcast ",
  mark:"Music",
  ratingNo:"673",
  free:"Free",  
},
]

// 10000000
const gameApi10=[{
  id:80,
  Nid:"1",
  img:"/ge1.png",
  title1:"Microsoft Store",
  title2:"Microsoft Corporation",
  Apps:"Apps",
  date:"Modified 2/17/2022",
  category:"Apps",
  
},
{
  id:81,
  Nid:"2",
  img:"/ge2.png",
  title1:"Skype",
  title2:"Skype",
  Apps:"Apps",
  date:"Modified 2/17/2022",
  category:"Apps",
  
},
{
  id:82,
  Nid:"3",
  img:"/ge3.png",
  title1:"Xbox Identity Provider",
  title2:"Microsoft Corporation",
  Apps:"Apps",
  date:"Modified 2/17/2022",
  category:"Apps",
  
},
{
  id:83,
  Nid:"4",
  img:"/ge4.png",
  title1:"Asphalt9: Legends",
  title2:"GAmeLoft SE",
  Apps:"Gaming",
  date:"Modified 2/13/2022",
  category:"game",
  
},
{
  id:84,
  Nid:"5",
  img:"/ge5.png",
  title1:"Microsoft Tips",
  title2:"Microsoft Corporation",
  Apps:"Apps",
  date:"Modified 2/11/2022",
  category:"Apps",
},
{
  id:85,
  Nid:"6",
  img:"/ge6.png",
  title1:"Microsoft Whiteboard",
  title2:"Microsoft Corporation",
  Apps:"Apps",
  date:"Modified 2/6/2022",
  category:"Apps",
  
},
{
  id:86,
  Nid:"7",
  img:"/ge7.png",
  title1:"Wps office",
  title2:"King soft Office",
  Apps:"Apps",
  date:"Modified 1/17/2022",
  category:"Apps",
  
},
{
  id:87,
  Nid:"8",
  img:"/ge8.png",
  title1:"Screen Recorder",
  title2:"Wuhan net power technology",
  Apps:"Apps",
  date:"Modified 2/23/2022",
  category:"Apps",
  
},
{
  id:88,
  Nid:"9",
  img:"/ge9.png",
  title1:"VLC UWP",
  title2:"VideoLan",
  Apps:"Apps",
  date:"Modified 1/19/2022",
  category:"Apps",
  
},
{
  id:89,
  Nid:"10",
  img:"/ge10.png",
  title1:"YouPlay - Youtube Player",
  title2:"Lion Group",
  Apps:"Apps",
  date:"Modified 9/18/2021",
  category:"Movie",
  
},
]
// 11111
const gameApi11=[{
  id:90,
  img:"/x1.png",
  title:"Grounded - Game Preview",
  mark:"Action & adventure",
  ratingNo:"380",
  free:"Included",  
},
{
id:91,
img:"/x2.png",
title:"Microsoft Flight Simulator",
mark:"Simulation",
ratingNo:"5k",
free:"Included",  
},
{
  id:92,
  img:"/x3.png",
  title:"Halo infinite(campaign)",
  mark:"Shooter",
  ratingNo:"4",
  free:"Included",  
},
{
  id:93,
  img:"/x4.png",
  title:"Wasteland 3",
  mark:"Role playing",
  ratingNo:"5k",
  free:"Free",  
},
{
  id:94,
  img:"/x5.png",
  title:"Halo infinite",
  mark:"Shooter",
  ratingNo:"1k",
  free:"Owned",  
},
{
  id:95,
  img:"/x6.png",
  title:"Psychonauts 2",
  mark:"Action & adventure",
  ratingNo:"673",
  free:"Included",  
},
{
  id:96,
  img:"/x7.png",
  title:"Gear of war",
  mark:"Shooter",
  ratingNo:"1k",
  free:"Free",  
},
{
  id:97,
  img:"/x8.png",
  title:"ORI - the collection",
  mark:"Action & adventure",
  ratingNo:"899",
  free:"Free",  
},
{
  id:98,
  img:"/x9.png",
  title:"Day of the tantacle",
  mark:"Action",
  ratingNo:"455",
  free:"$110",  
},
{
  id:99,
  img:"/x10.png",
  title:"Call of duty",
  mark:"Grim fandango Remasterd",
  ratingNo:"1k",
  free:"Free",  
},

]



export default gameApi;
export {gameApi4,gameApi3,gameApi5,gameApi6,gameApi7,gameApi8,gameApi9,gameApi10,gameApi11};


